### ISSUE TITLE
Please remove hard coded HTTP schema from wp-config.php WP_SITEURL/WP_HOME

### ISSUE THREAD

**Issue by dnauck** [bitnami/bitnami-docker-wordpress#187]
I've the following setup:

K8n + Wordpress Helm Chart + Nginx Ingress + CertManager

The Nginx ingress does the SSL termination.

Now there're two values hard coded in the **wp-config.php** that set the wordpress hostname/url with a HTTP scheme, but its HTTPS due the ingress.

```
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/');
```

You cannot even change the values from the WP backend, as they are greyed out.

So many plugins and themes have issues with this values, as they relay on this URLs to generate URLs for images or css, etc and this insecure content is blocked by your browser.

To name a few:

- Avada theme (avada backend not useable at all, due HTTP resource links)
- elementor complains (see also #186)
- Menu Icons plugin (renders fonts css with HTTP url, not HTTPS)
- WP All In One Migration (fix some times ago with a hack on their side)
- ...

Whats the reason to hard code HTTP in the read-only file? Can you please remove or change it to work with HTTP and HTTPS? It would be also very very helpful to ship a migration script that fixes this for older sites.

Thank you very much.

**Comment by juan131** [comment]
Hi @dnauck 

As you mentioned those values are hardcoded and, unless you access to one of the WP pods and use the **wp-cli tool** to update them there's no way to update it. For instance:

```console
$ kubectl exec -it $(kubectl get pods -l app=wordpress -o jsonpath='{.items[0].metadata.name}') -- /bin/bash
# sudo -u bitnami -i -- /opt/bitnami/wp-cli/bin/wp config get WP_SITEURL
https://127.0.0.1/
# sudo -u bitnami -i -- /opt/bitnami/wp-cli/bin/wp config get WP_HOME
http://127.0.0.1/
# sudo -u bitnami -i -- /opt/bitnami/wp-cli/bin/wp config set WP_SITEURL https://127.0.0.1/
Success: Updated the constant 'WP_SITEURL' in the 'wp-config.php' file with the value 'https://127.0.0.1/'.
# sudo -u bitnami -i -- /opt/bitnami/wp-cli/bin/wp config set WP_HOME https://127.0.0.1/
Success: Updated the constant 'WP_HOME' in the 'wp-config.php' file with the value 'https://127.0.0.1/'.
```

I guess we could implement some env. variable that allows setting `https` in the **wp-config.php**  the first time WordPress is initialized.

**Comment by dnauck** [comment]
Why are those values in wp-config.php at all? A normal WP install also don't have them?

**Comment by juan131** [comment]
Hi @dnauck 

We need those values to support accessing WordPress from different URLs (e.g. `127.0.0.1`, `SERVER_IP`, `example.com`, etc.)

**Comment by dnauck** [comment]
@juan131 then maybe also autodetect the Scheme, like the Domain name?

**Comment by juan131** [comment]
Do you mean a solution such as the one suggested on this blog @dnauck ? https://blog.rabin.io/sysadmin/make-wordpress-site-work-both-http-https

**Comment by dnauck** [comment]
Yes, maybe if that works.

Otherwise it would be possible to define those values during first startup like other stuff. (or write them into the database settings table like on a normal install)

**Comment by juan131** [comment]
> Otherwise it would be possible to define those values during first startup like other stuff. (or write them into the database settings table like on a normal install)

I think a solution such as the one I mentioned on a previous post could work:

> I guess we could implement some env. variable that allows setting https in the wp-config.php the first time WordPress is initialized.

Would it be ok for you if we work on adding that support to the WP image and chart?

**Comment by dnauck** [comment]
Yes, we can try if this works better for all plugins and themes.

It would be nice if the change also upgrades existing installations (without modifications)

**Comment by juan131** [comment]
I'm creating an internal task to work on this feature asap @dnauck 

Thanks so much for your feedback on this application! We'll keep you updated about our progress

**Comment by juan131** [comment]
Hi @dnauck 

We just released a new Docker image (**version 5.2.2-r35**) which accept a new env. variable **"WORDPRESS_SCHEME"** that you can set to **"http"** or **"https"** (see https://github.com/bitnami/bitnami-docker-wordpress#environment-variables). Using this env. variable you can specify what scheme to use in the **WP_SITEURL** and **WP_HOME** properties.

I also created a PR to add a parameter in the chart so you can easily choose the scheme. See https://github.com/helm/charts/pull/16136

**Comment by juan131** [comment]
Hi @dnauck 

The PR was merged so now you can use the parameter **wordpressScheme** to setup the scheme to use in the WP_SITEURL and WP_HOME properties.

Find more information in the [README.md](https://github.com/helm/charts/blob/master/stable/wordpress/README.md) file.

**Comment by venugopalthati** [comment]
@juan131  We are using docker.io/bitnami/wordpress:5.3.2-debian-10-r52 image and WORDPRESS_SCHEME environment variable configured as https but we still see WP_SITEURL and WP_HOME values are set with http protocol in wp-config.php. We have used the helm chart bitnami/wordpress with wordpressScheme value as https to deploy wordpress in Kubernetes. Could you please let us know if we are missing anything here ?

define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . '/');

**Comment by juan131** [comment]
Hi @venugopalthati 

I'm unable to reproduce the issue. I used the **docker-compose.yaml** below:

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5.3.2-debian-10-r52'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

Then, I run the commands below:

```console
$ docker-compose up -d
# Wait for WP to be initialized
$ docker-compose logs -f wordpress
# Once it's up and running
$ docker-compose exec wordpress grep "WP_SITEURL" /opt/bitnami/wordpress/wp-config.php
define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/');
$ docker-compose exec wordpress grep "WP_HOME" /opt/bitnami/wordpress/wp-config.php
define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/');
```

**Comment by venugopalthati** [comment]
@juan131 I am using Helm and Kubernetes, provided details below

Helm client version: 2.16.1
Helm server version: 2.16.1
Kubernetes client version: v1.15.0
Kubernetes server version: v1.13.5
Helm chart version for bitnami/wordpress: 9.0.4

Helm command used to install wordpress, attached the values file as well.

helm install --name wordpress --namespace wordpress -f <values file path> --version 9.0.4 bitnami/wordpress

 
[values-wordpress.txt](https://github.com/bitnami/bitnami-docker-wordpress/files/4380940/values-wordpress.txt)

**Comment by gbates101** [comment]
@juan131 I'm also running into this issue with deploying to Kubernetes. The `WORDPRESS_SCHEME` env var is being set appropriately in the pod, and the website will load (with no CSS). I'm also using chart version 9.0.4, but with image `bitnami/wordpress:5.3.2-debian-10-r48`. In my case, I am seeing https being defined in config located at `/opt/bitnami/wordpress/wp-config.php`:

```php
define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] . '/');
define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] . '/');
```

However, all URLs rendered server-side are still http (all requests fail with "mixed content" error).

**Comment by venugopalthati** [comment]
> @juan131 I am using Helm and Kubernetes, provided details below
> 
> Helm client version: 2.16.1
> Helm server version: 2.16.1
> Kubernetes client version: v1.15.0
> Kubernetes server version: v1.13.5
> Helm chart version for bitnami/wordpress: 9.0.4
> 
> Helm command used to install wordpress, attached the values file as well.
> 
> helm install --name wordpress --namespace wordpress -f values-file --version 9.0.4 bitnami/wordpress
> 
> [values-wordpress.txt](https://github.com/bitnami/bitnami-docker-wordpress/files/4380940/values-wordpress.txt)

@juan131 Note that initial installation was done using the scheme as http but later I have changed to https, not sure if this makes any difference.

**Comment by juan131** [comment]
> @juan131 Note that initial installation was done using the scheme as http but later I have changed to https, not sure if this makes any difference.

Yes, that makes a difference. WordPress is configured only during the 1st boot when you're persisting its data. After that, whenever the WP container is restarted, it'll reuse the existing data and configuration.

**Comment by venugopalthati** [comment]
> > @juan131 Note that initial installation was done using the scheme as http but later I have changed to https, not sure if this makes any difference.
> 
> Yes, that makes a difference. WordPress is configured only during the 1st boot when you're persisting its data. After that, whenever the WP container is restarted, it'll reuse the existing data and configuration.

@juan131 I did fresh installation with scheme as https, everything is working fine now. Thanks for your help.

**Comment by juan131** [comment]
You're welcome @venugopalthati !! I'm glad you could get it working!
